import type { NextPage } from "next";
import Head from "next/head";
import Dashboard from "../components/layouts/Dashboard";
import Footer from "../components/layouts/Footer";
import Header from "../components/layouts/Header";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Breze</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/breze-icon-test-black.png" />
      </Head>
      <Header />
      <Dashboard />
      <Footer />
    </div>
  );
};

export default Home;
